on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - .github/workflows/**
  #     - "*.sh"

# env:
#   release: ${{ GITHUB_SHA }}

jobs:
  macos:
    runs-on: macos-11
    environment: Actions
    strategy:
      matrix:
        build_type: [Release]
        arch: [ "x86_64", "arm64"]
      fail-fast: false
    env:
      platform: macos
      build_type: ${{ matrix.build_type }}
      arch: ${{ matrix.arch }}
      shared_suffix: "dylib"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.11.0.1100
      - run: "clojure -X com.phronemophobic.cef.env/compile-ceflib :arch ${{env.arch}}"
      - uses: actions/upload-artifact@v2
        with:
          name: "build-${{env.platform}}-${{env.arch}}"
          path: "csource/build-${{env.platform}}-${{env.arch}}"

  linux:
    runs-on: ubuntu-20.04
    environment: Actions
    strategy:
      matrix:
        build_type: [Release]
        arch: ["x86_64"]
      fail-fast: false
    env:
      platform: linux
      build_type: ${{ matrix.build_type }}
      arch: ${{ matrix.arch }}
      shared_suffix: "so"
    steps:
      - uses: actions/checkout@v2
      - run: sudo ./csource/prepare_linux.sh
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          # Install just one or all simultaneously
          cli: 1.11.0.1100
      - run: "clojure -X com.phronemophobic.cef.env/compile-ceflib :arch ${{env.arch}}"
      - uses: actions/upload-artifact@v2
        with:
          name: "build-${{env.platform}}-${{env.arch}}"
          path: "csource/build-${{env.platform}}-${{env.arch}}"
